# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d60b9d8e3b761041f4636d2432cc976028ad96f20446e0e4dda6ea25f89aa5bbc6d95ad778a7a0eeb866ddaaa173c342c950ae63e8faa32eda01c414dbeacd37

test:
  secret_key_base: 774a8c29f706fa754f117add1b76fa966bde2262eeec193c92df1899da5de0e0665da3dedce69ceb1b48bda2c9c7b17a303d3f110506f3867e552289b5dd4238

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 6f39e99e15ac03a84255edf6c46d87de8ec89d47ab9445e816ff4cd5b7b83445574958c836db9ea1ae134b132d60cdcb650fcc967b5e8ea96cf6cf0401f0571b
